---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels: 
        app: health-care
    spec:
      containers:
        - name: health-care
          image: mahithareddy/health-care:1.0
          ports: 
          - containerPort: 8082
          env:
            - name: PORT
              value: "8082"

---
apiVersion: v1
kind: Service
metadata:
  name: health-care-service
spec:
  selector:
    app: finance-app
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30085
  type: NodePort
  
